### PR TITLE
Add pre-commit config + update eslint

### PR DESCRIPTION
**Pull request by ianhi**
Should fix: https://github.com/cytoscape/ipycytoscape/issues/299

@marimeireles do you think the instructions on usage are through enough? I can add more - could also imagine adding instructions for what to do once the bot pushes to your PR.

I expect the checks to fail as this repo has some flake8 issues (which we could ignore by removing the flake8 check)

### CODE REVIEW

**Comment by ianhi** [comment]
oh boy: 
image

**Comment by ianhi** [comment]
The failing test is one that was actually never being run before and that I discovered wasn't being due to the flake8 checks. Confused by the python version dependency though

**Comment by marimeireles** [comment]
This is such a weird error 😅
Can't reproduce it locally
What's up with these CIs

**Comment by marimeireles** [comment]
I reran the test and now another python is unhappy for another weird reason.

**Comment by jenshnielsen** [comment]
I did a bit of experimenting on https://github.com/jenshnielsen/ipycytoscape/pull/4 and it looks like the test failure can be reproduced by only renameing the second test_add_edges to avoid collisions. It may be worthwile extracting that from this pr

**Comment by jenshnielsen** [comment]
#308 should resolve the test issue while still running all the tests

**Pull request merged**
